# Generated by Django 5.0 on 2023-12-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='created_at',
        ),
    ]
