# Generated by Django 5.0 on 2023-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_searchhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='wordcloud_image',
            field=models.ImageField(blank=True, null=True, upload_to='wordclouds/'),
        ),
    ]
